<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="90576" started-at="2018-11-26T14:34:22Z" finished-at="2018-11-26T14:35:52Z">
    <groups>
    </groups>
    <test name="TestSuite1" duration-ms="90576" started-at="2018-11-26T14:34:22Z" finished-at="2018-11-26T14:35:52Z">
      <class name="Railway.RegisterTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Railway.RegisterTest@343f4d3d]" name="beforeClass" is-config="true" duration-ms="7652" started-at="2018-11-26T14:35:14Z" finished-at="2018-11-26T14:35:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC01()[pri:0, instance:Railway.RegisterTest@343f4d3d]" name="TC01" duration-ms="14706" started-at="2018-11-26T14:35:21Z" description="User can create new account" finished-at="2018-11-26T14:35:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:Railway.RegisterTest@343f4d3d]" name="TC02" duration-ms="1971" started-at="2018-11-26T14:35:36Z" description="User can&#039;t create account with &quot;Confirm password&quot; is not the same with &quot;Password&quot;" finished-at="2018-11-26T14:35:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Railway.RegisterTest@343f4d3d]" name="afterClass" is-config="true" duration-ms="594" started-at="2018-11-26T14:35:38Z" finished-at="2018-11-26T14:35:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Railway.RegisterTest -->
      <class name="Railway.LoginTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Railway.LoginTest@57baeedf]" name="beforeClass" is-config="true" duration-ms="10465" started-at="2018-11-26T14:34:22Z" finished-at="2018-11-26T14:34:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC01()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC01" duration-ms="9399" started-at="2018-11-26T14:34:32Z" description="User can log into Railway with valid username and password" finished-at="2018-11-26T14:34:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC02" duration-ms="4256" started-at="2018-11-26T14:34:42Z" description="User can&#039;t login with blank &quot;Username&quot; textbox" finished-at="2018-11-26T14:34:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="FAIL" signature="TC03()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC03" duration-ms="1126" started-at="2018-11-26T14:34:46Z" description="User cannot log into Railway with invalid password" finished-at="2018-11-26T14:34:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Railway.LoginTest.TC03(LoginTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="TC04()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC04" duration-ms="2095" started-at="2018-11-26T14:34:47Z" description="Login page displays when un-logged User clicks on &quot;Book ticket&quot; tab" finished-at="2018-11-26T14:34:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC05" duration-ms="5474" started-at="2018-11-26T14:34:49Z" description="System shows message when user enters wrong password several times" finished-at="2018-11-26T14:34:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Railway.LoginTest.TC05(LoginTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="TC06()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC06" duration-ms="14818" started-at="2018-11-26T14:34:55Z" description="Additional pages display once user logged in" finished-at="2018-11-26T14:35:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06 -->
        <test-method status="PASS" signature="TC07()[pri:0, instance:Railway.LoginTest@57baeedf]" name="TC07" duration-ms="3430" started-at="2018-11-26T14:35:10Z" description="User can&#039;t login with an account hasn&#039;t been activated" finished-at="2018-11-26T14:35:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC07 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Railway.LoginTest@57baeedf]" name="afterClass" is-config="true" duration-ms="587" started-at="2018-11-26T14:35:13Z" finished-at="2018-11-26T14:35:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Railway.LoginTest -->
      <class name="Railway.ChangePasswordTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Railway.ChangePasswordTest@53b32d7]" name="beforeClass" is-config="true" duration-ms="8441" started-at="2018-11-26T14:35:38Z" finished-at="2018-11-26T14:35:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TC01()[pri:0, instance:Railway.ChangePasswordTest@53b32d7]" name="TC01" duration-ms="4894" started-at="2018-11-26T14:35:47Z" description="User can change password" finished-at="2018-11-26T14:35:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Your password has been updated must be displayed expected [Your password has been updated] but found [Your password has been updated!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Your password has been updated must be displayed expected [Your password has been updated] but found [Your password has been updated!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.ChangePasswordTest.TC01(ChangePasswordTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Railway.ChangePasswordTest@53b32d7]" name="afterClass" is-config="true" duration-ms="617" started-at="2018-11-26T14:35:52Z" finished-at="2018-11-26T14:35:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Railway.ChangePasswordTest -->
    </test> <!-- TestSuite1 -->
  </suite> <!-- Suite1 -->
</testng-results>
