<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="7" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38109" started-at="2018-11-21T15:11:23Z" finished-at="2018-11-21T15:12:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38109" started-at="2018-11-21T15:11:23Z" finished-at="2018-11-21T15:12:01Z">
      <class name="Railway.LoginTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeClass" is-config="true" duration-ms="8430" started-at="2018-11-21T15:11:23Z" finished-at="2018-11-21T15:11:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="786" started-at="2018-11-21T15:11:32Z" finished-at="2018-11-21T15:11:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC01()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC01" duration-ms="2273" started-at="2018-11-21T15:11:33Z" description="User can log into Railway with valid username and password" finished-at="2018-11-21T15:11:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="2565" started-at="2018-11-21T15:11:35Z" finished-at="2018-11-21T15:11:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC02" duration-ms="908" started-at="2018-11-21T15:11:37Z" description="User can&#039;t login with blank &quot;Username&quot; textbox" finished-at="2018-11-21T15:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="796" started-at="2018-11-21T15:11:38Z" finished-at="2018-11-21T15:11:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC03()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC03" duration-ms="1038" started-at="2018-11-21T15:11:39Z" description="User cannot log into Railway with invalid password" finished-at="2018-11-21T15:11:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message There was a problem with your login and/or errors exist in your form. must be displayed expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message There was a problem with your login and/or errors exist in your form. must be displayed expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC03(LoginTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="703" started-at="2018-11-21T15:11:40Z" finished-at="2018-11-21T15:11:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC04()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC04" duration-ms="1256" started-at="2018-11-21T15:11:41Z" description="Login page displays when un-logged User clicks on &quot;Book ticket&quot; tab" finished-at="2018-11-21T15:11:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC04 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="686" started-at="2018-11-21T15:11:42Z" finished-at="2018-11-21T15:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC05" duration-ms="4888" started-at="2018-11-21T15:11:43Z" description="System shows message when user enters wrong password several times" finished-at="2018-11-21T15:11:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes. must be displayed expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes. must be displayed expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC05(LoginTest.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="756" started-at="2018-11-21T15:11:48Z" finished-at="2018-11-21T15:11:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC06()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC06" duration-ms="3590" started-at="2018-11-21T15:11:48Z" description="Additional pages display once user logged in" finished-at="2018-11-21T15:11:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Change password page is not displayed expected [Changepassword] but found [Change password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Change password page is not displayed expected [Changepassword] but found [Change password]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Railway.LoginTest.TC06(LoginTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06 -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:Railway.LoginTest@1794d431]" name="beforeMethod" is-config="true" duration-ms="2448" started-at="2018-11-21T15:11:52Z" finished-at="2018-11-21T15:11:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TC07()[pri:0, instance:Railway.LoginTest@1794d431]" name="TC07" duration-ms="6282" started-at="2018-11-21T15:11:54Z" description="User can create new account" finished-at="2018-11-21T15:12:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC07 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Railway.LoginTest@1794d431]" name="afterClass" is-config="true" duration-ms="673" started-at="2018-11-21T15:12:01Z" finished-at="2018-11-21T15:12:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Railway.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
